import { ALL_PUBLIC_PAGES, type BrandClaim } from './types'

export const FULFILLMENT_SCALE_CLAIMS = {
  warehouseArea: {
    claimKey: 'direct_operated_warehouse_area',
    displayValue: '54万㎡',
    rawValue: 540000,
    unit: '㎡',
    scope: '全网直营仓储面积',
    periodStart: null,
    periodEnd: null,
    sourceType: 'company_material',
    sourceReference: '业务负责人更新（2026-08-08）',
    verifiedBy: '业务负责人',
    verifiedAt: '2026-08-08',
    expiresAt: null,
    publishStatus: 'approved',
    allowedPages: ALL_PUBLIC_PAGES,
    notes: '统计周期待仓储资产台账补录；不得拆算为未经验证的地区仓面积。',
  },
  partnerBrands: {
    claimKey: 'partner_brand_count',
    displayValue: '150+',
    rawValue: 150,
    unit: '家',
    scope: '合作品牌数量',
    periodStart: null,
    periodEnd: null,
    sourceType: 'company_material',
    sourceReference: '业务负责人更新（2026-08-08）',
    verifiedBy: '业务负责人',
    verifiedAt: '2026-08-08',
    expiresAt: null,
    publishStatus: 'approved',
    allowedPages: ALL_PUBLIC_PAGES,
    notes: '统计周期待合作品牌台账补录。',
  },
  servedStores: {
    claimKey: 'served_store_count',
    displayValue: '10000+',
    rawValue: 10000,
    unit: '家',
    scope: '服务门店数量',
    periodStart: null,
    periodEnd: null,
    sourceType: 'company_material',
    sourceReference: '资料库.md（2026-07-27）',
    verifiedBy: '业务负责人',
    verifiedAt: '2026-07-27',
    expiresAt: null,
    publishStatus: 'approved',
    allowedPages: ALL_PUBLIC_PAGES,
    notes: '统计周期待运营台账补录。',
  },
  managedSkus: {
    claimKey: 'managed_sku_count',
    displayValue: '45万+',
    rawValue: 450000,
    unit: 'SKU',
    scope: '管理SKU数量',
    periodStart: null,
    periodEnd: null,
    sourceType: 'company_material',
    sourceReference: '资料库.md（2026-07-27）',
    verifiedBy: '业务负责人',
    verifiedAt: '2026-07-27',
    expiresAt: null,
    publishStatus: 'approved',
    allowedPages: ALL_PUBLIC_PAGES,
    notes: '统计周期待运营台账补录。',
  },
  coveredCities: {
    claimKey: 'covered_city_count',
    displayValue: '6000+',
    rawValue: 6000,
    unit: '个',
    scope: '仓配与运输服务覆盖城市数量',
    periodStart: null,
    periodEnd: null,
    sourceType: 'company_material',
    sourceReference: '资料库.md（2026-07-27）',
    verifiedBy: '业务负责人',
    verifiedAt: '2026-07-27',
    expiresAt: null,
    publishStatus: 'approved',
    allowedPages: ALL_PUBLIC_PAGES,
    notes: '统计周期待线路台账补录；具体线路和可达范围按项目核验。',
  },
  employeeCount: {
    claimKey: 'employee_count',
    displayValue: '1500+',
    rawValue: 1500,
    unit: '名',
    scope: '员工规模',
    periodStart: null,
    periodEnd: null,
    sourceType: 'user_confirmation',
    sourceReference: '业务负责人更新（2026-08-08）',
    verifiedBy: '业务负责人',
    verifiedAt: '2026-08-08',
    expiresAt: null,
    publishStatus: 'approved',
    allowedPages: ALL_PUBLIC_PAGES,
    notes: '统计周期待人力台账补录；公开展示使用1500+名员工口径。',
  },
} as const satisfies Record<string, BrandClaim>
