import { ALL_PUBLIC_PAGES, type BrandClaim } from './types'

export const FULFILLMENT_PERFORMANCE_CLAIMS = {
  shippingSla: {
    claimKey: 'shipping_sla',
    displayValue: '18:00前截单，当日24:00前发出',
    rawValue: '18:00/24:00',
    unit: '',
    scope: '正向订单履约',
    periodStart: null,
    periodEnd: null,
    sourceType: 'user_confirmation',
    sourceReference: 'SEO/GEO上线审计 E-003；用户于2026-07-28确认',
    verifiedBy: '业务负责人',
    verifiedAt: '2026-07-28',
    expiresAt: null,
    publishStatus: 'approved',
    allowedPages: ALL_PUBLIC_PAGES,
    notes: '履约规则不适用单一统计周期；不得改写为17:00或当日揽收。',
  },
  shippingAccuracy: {
    claimKey: 'shipping_accuracy',
    displayValue: '99.99%',
    rawValue: 99.99,
    unit: '%',
    scope: '发货准确率',
    periodStart: null,
    periodEnd: null,
    sourceType: 'company_material',
    sourceReference: '资料库.md（2026-07-27）',
    verifiedBy: '业务负责人',
    verifiedAt: '2026-07-27',
    expiresAt: null,
    publishStatus: 'approved',
    allowedPages: ALL_PUBLIC_PAGES,
    notes: '统计周期待经营数据报告补录。',
  },
  inventoryAccuracy: {
    claimKey: 'inventory_accuracy',
    displayValue: '99.99%',
    rawValue: 99.99,
    unit: '%',
    scope: '库存准确率',
    periodStart: null,
    periodEnd: null,
    sourceType: 'company_material',
    sourceReference: '资料库.md（2026-07-27）',
    verifiedBy: '业务负责人',
    verifiedAt: '2026-07-27',
    expiresAt: null,
    publishStatus: 'approved',
    allowedPages: ALL_PUBLIC_PAGES,
    notes: '统计周期待经营数据报告补录。',
  },
  singleWarehousePeak: {
    claimKey: 'single_warehouse_daily_peak',
    displayValue: '50万单/日',
    rawValue: 500000,
    unit: '单/日',
    scope: '实际单仓单日运营峰值',
    periodStart: null,
    periodEnd: null,
    sourceType: 'company_material',
    sourceReference: '资料库.md（2026-07-27）',
    verifiedBy: '业务负责人',
    verifiedAt: '2026-07-27',
    expiresAt: null,
    publishStatus: 'approved',
    allowedPages: ALL_PUBLIC_PAGES,
    notes: '统计周期待运营峰值记录补录；不得与WMS系统容量混写。',
  },
  regionalPeak: {
    claimKey: 'regional_daily_peak',
    displayValue: '100万单/日',
    rawValue: 1000000,
    unit: '单/日',
    scope: '地区单日运营峰值',
    periodStart: null,
    periodEnd: null,
    sourceType: 'company_material',
    sourceReference: '资料库.md（2026-07-27）',
    verifiedBy: '业务负责人',
    verifiedAt: '2026-07-27',
    expiresAt: null,
    publishStatus: 'approved',
    allowedPages: ALL_PUBLIC_PAGES,
    notes: '统计周期待地区运营峰值记录补录；不得表述为日常发货量。',
  },
} as const satisfies Record<string, BrandClaim>
