import { ALL_PUBLIC_PAGES, type BrandClaim } from './types'

export const QUALITY_CLAIMS = {
  returnTurnaround: {
    claimKey: 'return_inspection_relisting_sla',
    displayValue: '24小时',
    rawValue: 24,
    unit: '小时',
    scope: '退货质检与二次上架整体流程',
    periodStart: null,
    periodEnd: null,
    sourceType: 'company_material',
    sourceReference: '资料库.md（2026-07-27）',
    verifiedBy: '业务负责人',
    verifiedAt: '2026-07-27',
    expiresAt: null,
    publishStatus: 'approved',
    allowedPages: ALL_PUBLIC_PAGES,
    notes: '服务规则不适用单一统计周期；不拆分为未经确认的固定等级时效。',
  },
  returnInspectionAnnual: {
    claimKey: 'annual_return_inspection_volume',
    displayValue: '1.53亿件',
    rawValue: 153000000,
    unit: '件',
    scope: '全年退货质检量',
    periodStart: null,
    periodEnd: null,
    sourceType: 'company_material',
    sourceReference: '资料库.md（2026-07-27）',
    verifiedBy: '业务负责人',
    verifiedAt: '2026-07-27',
    expiresAt: null,
    publishStatus: 'approved',
    allowedPages: ALL_PUBLIC_PAGES,
    notes: '具体统计年度待经营数据报告补录，不在页面虚构年份。',
  },
  newGoodsInspectionAnnual: {
    claimKey: 'annual_new_goods_inspection_volume',
    displayValue: '1.17亿件',
    rawValue: 117000000,
    unit: '件',
    scope: '全年新货质检量',
    periodStart: null,
    periodEnd: null,
    sourceType: 'company_material',
    sourceReference: '资料库.md（2026-07-27）',
    verifiedBy: '业务负责人',
    verifiedAt: '2026-07-27',
    expiresAt: null,
    publishStatus: 'approved',
    allowedPages: ALL_PUBLIC_PAGES,
    notes: '具体统计年度待经营数据报告补录，不在页面虚构年份。',
  },
  recognizableAnomalies: {
    claimKey: 'recognizable_anomaly_count',
    displayValue: '135+种',
    rawValue: 135,
    unit: '种',
    scope: '可识别鞋服异常类型',
    periodStart: null,
    periodEnd: null,
    sourceType: 'company_material',
    sourceReference: '资料库.md（2026-07-27）',
    verifiedBy: '业务负责人',
    verifiedAt: '2026-07-27',
    expiresAt: null,
    publishStatus: 'approved',
    allowedPages: ALL_PUBLIC_PAGES,
    notes: '统计周期待质检能力台账补录；只代表识别能力，不代表全部可以修复。',
  },
  repairSuccessRate: {
    claimKey: 'repair_success_rate',
    displayValue: '90%',
    rawValue: 90,
    unit: '%',
    scope: '瑕疵修复成功率',
    periodStart: null,
    periodEnd: null,
    sourceType: 'company_material',
    sourceReference: '资料库.md（2026-07-27）',
    verifiedBy: '业务负责人',
    verifiedAt: '2026-07-27',
    expiresAt: null,
    publishStatus: 'approved',
    allowedPages: ALL_PUBLIC_PAGES,
    notes: '统计周期及样本范围待修复项目报表补录。',
  },
} as const satisfies Record<string, BrandClaim>
