import type { SiteLocale } from '@/i18n/routes'

export const LIVE_UI_COPY = {
  'zh-CN': {
    scenesLabel: '适用场景',
    scenes: ['品牌自播', '达人带货', 'MCN · 代播'],
    contact: '咨询直播仓配',
    serviceVideo: '服务视频',
    stagesKicker: '场次安排',
    stagesHeading: '开播前准备好，出单后跟得上',
    stagesLabel: '直播仓配阶段',
    stages: [
      [
        '开播前',
        '货、包材与人手，提前安排',
        '根据场次计划核对预计订单、SKU 与库存，安排包材与人员。',
      ],
      ['集中出单', '订单集中来，仓内有序做', '订单校验后，按波次组织拣货与出库复核。'],
      ['发货跟进', '按约定发货，异常及时跟进', '安排截单、打包出库、异常跟进与状态回传。'],
    ],
    sync: [
      '库存同步',
      '多平台出单，库存也要跟上',
      '连接订单、库存与发货状态，减少多平台卖货时的信息差。',
      '订单接入',
      '根据项目确认订单、库存、发货与退货数据的衔接范围。',
      '发货回传',
      '仓内完成校验、波次、复核与出库后，按项目约定回传状态。',
    ],
    returns: [
      '退货处理',
      '退回来的商品，也有下一步',
      '拆包核对、质检分级后，根据商品状态安排整理与二次上架。',
      '可售商品',
      '按规则完成复核与二次上架。',
      '需要整理的商品',
      '根据质检结果安排整理，需修复的另行评估。',
      '异常商品',
      '记录问题并确认后续处理方式。',
      '了解退货质检',
      '了解后整修复',
    ],
    mcn: [
      '多品牌管理',
      '多品牌一起运营，',
      '管理各自清楚',
      '适合 MCN 与代播团队。',
      '商品如何分开',
      '按品牌分区管理货品。',
      '账号能看什么',
      '按品牌配置库存和订单查看权限。',
      '出库与对账',
      '品牌独立出库单与报表。',
      '如何结算',
      '可沟通统一结算或各品牌分别结算。',
      '代播机构可统一结算，也可由各品牌分别结算；具体方案按品牌数量与SKU规模确认。',
    ],
    faqKicker: '常见问题',
    faqHeading: '开始合作前，你可能还想了解',
    ctaEyebrow: '提前准备',
    ctaLines: ['下一场直播，', '提前把仓配安排好'],
    ctaDesc: '告诉我们开播时间、预计订单、商品种类和平台，一起安排备货与发货。',
    prep: [
      ['开播时间', '场次日期与备货节奏'],
      ['预计订单', '日常订单与活动预估'],
      ['商品种类与平台', '商品种类与销售平台'],
    ],
    cases: '查看合作案例',
    services: '查看全部仓配服务',
    unavailable: '服务内容暂不可用',
  },
  en: {
    scenesLabel: 'Suitable for',
    scenes: ['Brand-operated livestreams', 'Creator-led selling', 'MCNs and livestream agencies'],
    contact: 'Discuss livestream fulfilment',
    serviceVideo: 'service video',
    stagesKicker: 'Session arrangement',
    stagesHeading: 'Prepare before going live, then keep up with orders',
    stagesLabel: 'Livestream fulfilment stages',
    stages: [
      [
        'Before going live',
        'Prepare stock, packing materials and staffing',
        'Review projected orders, SKUs and inventory against the session plan, then arrange packing materials and staffing.',
      ],
      [
        'Concentrated order flow',
        'Keep warehouse operations orderly as orders arrive',
        'After order checks, organise picking and dispatch verification in work waves.',
      ],
      [
        'Dispatch follow-up',
        'Dispatch as agreed and follow up on exceptions',
        'Arrange order cut-off, packing, outbound dispatch, exception follow-up and status updates.',
      ],
    ],
    sync: [
      'Inventory synchronisation',
      'Keep inventory aligned as orders arrive across platforms',
      'Connect order, inventory and dispatch status to reduce information gaps when selling across platforms.',
      'Order integration',
      'Confirm the project scope for connecting order, inventory, dispatch and returns data.',
      'Dispatch status update',
      'After warehouse checks, waves, verification and outbound dispatch, return status updates as agreed for the project.',
    ],
    returns: [
      'Returns handling',
      'Every returned item has a next step',
      'After unpacking checks and inspection grading, arrange finishing and re-listing according to item condition.',
      'Saleable items',
      'Complete checks and re-listing under the agreed rules.',
      'Items needing finishing',
      'Arrange finishing based on inspection results; assess items needing repair separately.',
      'Exception items',
      'Record the issue and confirm the next handling method.',
      'Explore returns inspection',
      'Explore garment care',
    ],
    mcn: [
      'Multi-brand management',
      'Operate multiple brands,',
      'while keeping each one clear',
      'For MCNs and livestream agencies.',
      'How goods are separated',
      'Manage goods in zones by brand.',
      'What each account can view',
      'Configure inventory and order-view permissions by brand.',
      'Dispatch and reconciliation',
      'Use separate dispatch notes and reports for each brand.',
      'Settlement options',
      'Discuss central settlement or separate settlement for each brand.',
      'Livestream agencies can settle centrally or each brand can settle separately; the arrangement is confirmed by brand count and SKU scale.',
    ],
    faqKicker: 'Frequently asked questions',
    faqHeading: 'More to confirm before starting',
    ctaEyebrow: 'Prepare in advance',
    ctaLines: ['Plan fulfilment for your next', 'livestream before it starts'],
    ctaDesc:
      'Share the livestream schedule, projected order volume, product types and platforms so we can arrange stock preparation and dispatch.',
    prep: [
      ['Livestream schedule', 'Session date and stock-preparation rhythm'],
      ['Projected orders', 'Routine orders and campaign forecast'],
      ['Product types and platforms', 'Product types and sales platforms'],
    ],
    cases: 'View cases',
    services: 'Explore services',
    unavailable: 'Service content is currently unavailable.',
  },
} as const

export function liveUi(locale: SiteLocale = 'zh-CN') {
  return LIVE_UI_COPY[locale]
}
